name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ticketResto pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 40
        env:
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Run backend test
              run: |
                  chmod +x gradlew
                  ./gradlew clean test integrationTest
            - name: Package application
              run: ./gradlew bootJar -Pprod -x test -x integrationTest
